[tool.poetry]
name = "CLI-Importer"
version = "0.9"
description = ""
authors = ["OSM@HPI"]
packages = [{include = "cli_importer"}]

[tool.poetry.dependencies]
python = "^3.10"
yaramo = {git = "https://github.com/simulate-digital-rail/yaramo.git"}

[tool.poetry.group.dev.dependencies]
yaramo = {git = "https://github.com/simulate-digital-rail/yaramo.git"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
