[tool.poetry]
name = "CLI-Importer"
version = "0.9"
description = ""
authors = ["OSM HPI <OSM@HPI>"]
packages = [{include = "cli_importer"}]

[tool.poetry.dependencies]
python = "^3.10"
yaramo = {git = "https://github.com/antonykamp/yaramo", branch="refactor/replace-connected-nodes-with-edges"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
